server:
  port: 8888
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/microService-NguyenNgocTri/cloud-config-service-user-department
          default-label: main
        bootstrap: false